import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/context/userContext";
import { Space_Grotesk } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-spaceGrotesk",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <UserProvider>
        <html lang="en">
          <body className={`bg-[#1A1919] ${spaceGrotesk.variable}`}>
            <div className="min-h-[100vh] max-w-screen-md mx-auto">
              {children}
            </div>
            <Toaster />
          </body>
        </html>
      </UserProvider>
    </SessionProvider>
  );
}
